SPECIAL>NOINTERACTION

SPECIAL>LOADMODEL|community corona 8.vmf
SPECIAL>CLEARRUNS
SIMULATE>ADDDATA|historical.vdf

SIMULATE>RUNNAME|Calibration.vdf
SIMULATE>PAYOFF|calib.vpd
SIMULATE>OPTPARM|calib.voc
MENU>RUN_OPTIMIZE|o

SIMULATE>RUNNAME|Baseline.vdf
SIMULATE>ADDCIN|Calibration.out
MENU>RUN

SPECIAL>CLEARRUNS
SPECIAL>LOADRUN|Baseline.vdf
SPECIAL>LOADRUN|Historical.vdf

SIMULATE>RUNNAME|Current.vdf
