"""{message}

Revision ID: aa82937bcbdd
Revises: fabee32631cc
Create Date: 2020-04-16 01:16:27.084685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa82937bcbdd'
down_revision = 'fabee32631cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('behavioral_risk_reduction', sa.Float(), nullable=True),
    sa.Column('potential_isolation_effectiveness', sa.Float(), nullable=True),
    sa.Column('run_id', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Unicode(), nullable=False),
    sa.Column('json_data', sa.Unicode(), nullable=True),
    sa.Column('run_id', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('steps',
    sa.Column('id', sa.Unicode(), nullable=False),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('susceptible', sa.Float(), nullable=True),
    sa.Column('exposed', sa.Float(), nullable=True),
    sa.Column('infected', sa.Float(), nullable=True),
    sa.Column('recovered', sa.Float(), nullable=True),
    sa.Column('deaths', sa.Float(), nullable=True),
    sa.Column('results_id', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['results_id'], ['results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('owners')
    op.add_column('runs', sa.Column('params', sa.Unicode(), nullable=True))
    op.add_column('runs', sa.Column('results', sa.Unicode(), nullable=True))
    op.add_column('runs', sa.Column('selected_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'selected_time')
    op.drop_column('runs', 'results')
    op.drop_column('runs', 'params')
    op.create_table('owners',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('run', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['run'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('steps')
    op.drop_table('results')
    op.drop_table('params')
    # ### end Alembic commands ###
